name: minimis-project
recipe: drupal9
config:
  webroot: web
  database: mariadb:10.5
  via: nginx
  php: 7.4
  composer_version: 2
services:
  appserver:
    run:
      - "cd /app && composer install"
