name: minimis-project
recipe: drupal8
config:
  webroot: web
  database: mariadb
  via: nginx
  php: 7.3
  composer_version: '1.10.17'
services:
  appserver:
    run:
      - "cd /app && composer install"
