# Change this name to something that makes sense for your project
name: minimis

# Use the recipe appropriate for your application.
recipe: drupal8

# Configure the D8 recipe to match up closer to a vanilla platform.sh stack
config:

  # Lando defaults to Apache. Switch to nginx to match Platform.sh.
  via: nginx

  # Set the webroot to match your .platform.app.yaml.
  webroot: web

  # Set this to match the version in your .platform.app.yaml.
  php: 7.1

  # Lando defaults to the latest MySQL release, but Platform.sh uses MariaDB.
  # Specify the version to match what's in services.yaml.
  database: mariadb:10.1

# The following additional build step will install the Platform CLI
# in the application container and auto-run `composer install`
services:
  appserver:
    build:
      - "cd $LANDO_MOUNT && composer install"
      - "cd $LANDO_MOUNT/web/profiles/minimis && composer install"

# Ensure `composer install` also happens every time you start your site
events:
  post-db-import:
    - appserver:
      - "cd $LANDO_MOUNT && composer install"
      - "cd $LANDO_MOUNT/web/profiles/minimis && composer install"

# The following entry creates a `lando platform` command that will run
# any Platform CLI command from inside the container if desired.
tooling:
  phplint:
    service: appserver
    cmd: /app/vendor/bin/phplint
  phpcs:
    service: appserver
    cmd: /app/vendor/bin/phpcs
  phpunit:
    service: appserver
    cmd: /app/vendor/bin/phpunit
  behat:
    service: appserver
    cmd: /app/vendor/bin/behat