# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    machine:
      image: circleci/classic:edge

    working_directory: ~/minimis

    steps:
      - checkout

      - run:
          name: Setup Lando
          command: |
            sudo apt-get -y update
            sudo apt-get -y install cgroup-bin curl
#            curl -fsSL -o /tmp/lando.deb https://github.com/lando/lando/releases/download/v3.0.0-beta.39/lando-v3.0.0-beta.39.deb
#            sudo dpkg -i /tmp/lando.deb
#            lando version

      - add_ssh_keys:
          fingerprints:
            - "cf:8f:40:b2:3f:6e:09:a0:0c:ab:5d:84:be:98:7d:e4"

      - run:
          name: Prep For Pushing
          command: |
            git config --global user.email labboy0276@yahoo.com
            git config --global user.name "John Ouellet"
            git remote add drupalorg git@git.drupal.org:project/minimis.git
            git fetch drupalorg

      - run:
          name: Move Files & Start Lando
          command: |
            rm -rf README.md
            cp -rf .circleci/.lando.yml .lando.yml
            lando start -- -v

      - run:
          name: Push to Drupal.org
          command: |
            git fetch drupalorg
            git add -A
            git commit -m "Compiling and Pushing from CircleCI"
            git pull drupalorg 8.x-1.x --rebase
            git push drupalorg 8.x-1.x