# The 'type' should be "label" for short meta tags and "text" for ones which
# could get longer, especially ones which use a textarea field instead of a
# textfield.
metatag.metatag_tag.schema_program_membership_additional_type:
  type: label
  label: 'additionalType'
metatag.metatag_tag.schema_program_membership_alternate_name:
  type: label
  label: 'alternateName'
metatag.metatag_tag.schema_program_membership_description:
  type: text
  label: 'description'
metatag.metatag_tag.schema_program_membership_disambiguating_description:
  type: text
  label: 'disambiguatingDescription'
metatag.metatag_tag.schema_program_membership_hosting_organization:
  type: text
  label: 'hostingOrganization'
metatag.metatag_tag.schema_program_membership_identifier:
  type: label
  label: 'identifier'
metatag.metatag_tag.schema_program_membership_image:
  type: text
  label: 'image'
metatag.metatag_tag.schema_program_membership_main_entity_of_page:
  type: label
  label: 'mainEntityOfPage'
metatag.metatag_tag.schema_program_membership_member:
  type: text
  label: 'member'
metatag.metatag_tag.schema_program_membership_membership_number:
  type: label
  label: 'membershipNumber'
metatag.metatag_tag.schema_program_membership_name:
  type: label
  label: 'name'
metatag.metatag_tag.schema_program_membership_program_name:
  type: label
  label: 'programName'
metatag.metatag_tag.schema_program_membership_same_as:
  type: text
  label: 'sameAs'
metatag.metatag_tag.schema_program_membership_type:
  type: text
  label: '@type'
metatag.metatag_tag.schema_program_membership_url:
  type: text
  label: 'url'
